[35;21m2023-11-22 16:33:38,338 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (h5.py:629): Quitting run() execution on Exception (PermissionError): [Errno 13] Unable to open file (unable to open file: name = 'C:\Users\hp\Desktop\M2 ISI\TSI\son\TP2\1_1050Hz_0_50cm-20231122-142234.h5', errno = 13, error message = 'Permission denied', flags = 0, o_flags = 0)[0m
[35;21m2023-11-22 19:57:38,569 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-22 19:57:38,571 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-22 19:57:38,571 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-22 19:57:38,591 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-22 19:57:38,577 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-22 19:57:38,579 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-22 19:57:38,580 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-22 19:57:38,583 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-22 19:57:38,584 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-22 19:57:38,585 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-22 19:57:38,585 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-22 19:57:38,576 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (ws.py:648):  Listening loop stopped due to network error exception (ConnectionClosedError): no close frame received or sent[0m
[35;21m2023-11-24 16:28:59,092 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (h5.py:629): Quitting run() execution on Exception (MemoryError): Unable to allocate 625. KiB for an array with shape (8, 20000) and data type int32[0m
[35;21m2023-11-25 13:25:02,485 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (h5.py:629): Quitting run() execution on Exception (MemoryError): Unable to allocate 625. KiB for an array with shape (8, 20000) and data type int32[0m
[35;21m2023-11-25 18:15:51,592 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (h5.py:629): Quitting run() execution on Exception (PermissionError): [Errno 13] Unable to open file (unable to open file: name = 'C:\Users\hp\Desktop\M2 ISI\TSI\son\TP2\1050_135_50cm.h5', errno = 13, error message = 'Permission denied', flags = 0, o_flags = 0)[0m
[35;21m2023-11-26 10:40:24,058 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (h5.py:629): Quitting run() execution on Exception (MemoryError): Unable to allocate 625. KiB for an array with shape (8, 20000) and data type int32[0m
[35;21m2023-11-26 10:40:24,058 [0m[30;1m[ERROR]: [0m[31;21min megamicros.log (h5.py:629): Quitting run() execution on Exception (MemoryError): Unable to allocate 625. KiB for an array with shape (8, 20000) and data type int32[0m
